#!/bin/bash

scp_host=baron.su
scp_path_img=/home/baron.su/public_html/s/
scp_path_vid=/path/to/videos
scp_path_paste=/path/to/pastes
http_img=https://baron.su/s
http_vid=https://YOUR_DOMAIN/path/to/videos
http_paste=https://YOUR_DOMAIN/path/to/pastes
